[2023-12-19T11:31:40.457+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2023-12-19T11:31:40.778+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2023-12-19T11:31:40.785+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-19T11:31:41.144+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_json_file> on 2023-01-25 00:00:00+00:00
[2023-12-19T11:31:41.292+0000] {standard_task_runner.py:57} INFO - Started process 381 to run task
[2023-12-19T11:31:41.534+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_json_file', 'scheduled__2023-01-25T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmpnvaw2jlb']
[2023-12-19T11:31:42.797+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask sense_json_file
[2023-12-19T11:31:55.887+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-12-19T11:32:04.055+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.sense_json_file scheduled__2023-01-25T00:00:00+00:00 [running]> on host e1038f319166
